RPython traceback:
  File "rpython_jit_metainterp.c", line 18589, in MIFrame_run_one_step
  File "rpython_jit_metainterp.c", line 24328, in handler_getfield_gc_i_pure
  File "rpython_jit_metainterp_1.c", line 15131, in _opimpl_getfield_gc_any_pureornot___156_i
  File "rpython_jit_metainterp_1.c", line 24051, in execute_and_record___156_star_1
  File "rpython_jit_backend_llsupport.c", line 7466, in bh_getfield_gc_i___ptr
Fatal RPython error: AssertionError
